name: whisper_env
channels:
  - defaults
dependencies:
  - _pytorch_select=1.2.0
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - aom=3.12.1
  - apricot-select=0.6.1
  - arrow-cpp=21.0.0
  - asttokens=3.0.0
  - attrs=25.4.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - blas=1.0
  - bottleneck=1.4.2
  - branca=0.8.1
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.4
  - cairo=1.18.4
  - captum=0.7.0
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cycler=0.11.0
  - datasets=3.3.2
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - dill=0.3.8
  - executing=2.2.1
  - expat=2.7.3
  - ffmpeg=6.1.1
  - filelock=3.20.0
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - frozenlist=1.8.0
  - fsspec=2024.12.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - hf-xet=1.1.8
  - huggingface_hub=0.34.4
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=6.31.0
  - ipylab=1.0.0
  - ipyleaflet=0.17.4
  - ipympl=0.9.7
  - ipyparallel=9.0.2
  - ipython=9.7.0
  - ipython_genutils=0.2.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.9
  - lcms2=2.16
  - lerc=3.0
  - libabseil=20250127.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.16.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libglib=2.84.4
  - libgrpc=1.71.0
  - libhwloc=2.12.1
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libllvm20=20.1.8
  - libogg=1.3.5
  - libpng=1.6.50
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libtheora=1.2.0
  - libthrift=0.22.0
  - libtiff=4.5.1
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lightning-utilities=0.15.2
  - llvmlite=0.44.0
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.2.1
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.7.0
  - multiprocess=0.70.15
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nose=1.3.7
  - numba=0.61.2
  - numexpr=2.11.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.18
  - opentelemetry-api=1.38.0
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pcre2=10.46
  - pillow=11.1.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - pomegranate=1.1.2
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - propcache=0.3.1
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pyarrow=21.0.0
  - pycares=4.10.0
  - pycparser=2.23
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - pytz=2025.2
  - pywin32=311
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - re2=2024.07.02
  - regex=2025.9.1
  - requests=2.32.5
  - safetensors=0.6.2
  - scikit-learn=1.7.1
  - scipy=1.16.0
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.5.1
  - snappy=1.2.1
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tbb-devel=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - tokenizers=0.22.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - traittypes=0.2.3
  - transformers=4.57.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - win_inet_pton=1.1.0
  - winloop=0.3.1
  - xxhash=0.8.0
  - xyzservices=2025.4.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.22.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - intel-openmp==2021.4.0
      - mkl==2021.4.0
      - more-itertools==10.8.0
      - openai-whisper==20250625
      - sympy==1.13.1
      - tbb==2021.11.0
      - tiktoken==0.12.0
      - torch==2.5.1+cu118
      - torchaudio==2.5.1+cu118
      - torchvision==0.20.1+cu118
      - yt-dlp==2025.11.12
prefix: C:\Users\yyomn\anaconda3\envs\whisper_env
